config/routes.rb
Rails.application.routes.draw do
  root "summoners#new"
  resources :summoners, only: [:new, :show, :create]
  resources :teams, only: [:show]

end

app/models/summoner.rb
class Summoner < ActiveRecord::Base
  has_many :rosters
  has_many :teams, through: :rosters

  validates :riot_id, presence: true, uniqueness: true
  validates :name, presence: true

  def self.add id_array
    all_summoners = {}
    split = id_array.each_slice(39).to_a
    split.each do |array|
      id_list = ""
      array.each do |id|
        id_list << id.to_s << ","
      end
      all_summoners.merge!(Riot.summoner_id(id_list))
      # is this api call necessary?
    end
    player_list_to_return = []
    all_summoners.each do |_id, s|
      player = Summoner.find_or_create_by(riot_id: s["id"], name: s["name"])
      player_list_to_return << player
    end
    return player_list_to_return
  end
end

app/controllers/summoners_controller.rb
class SummonersController < ApplicationController
  def show
    @summoner = Summoner.find(params[:id])
    @teams = @summoner.teams
  end

  def new
    @summoner = Summoner.new
  end

  def create
    name = summoner_params[:name]
    if Summoner.exists?(name: name)
      @summoner = Summoner.find_by(name: name)
    else
      summoner_info = Riot.summoner_name(name)
      if !summoner_info.nil?
        summoner_info = summoner_info[Riot.standardize(name)]
        params = { riot_id: summoner_info["id"], name: summoner_info["name"] }
        @summoner = Summoner.find_or_create_by(params)
        if @summoner.save
          flash[:notice] = "Welcome!"
        else
          @summoner = nil
        end
      end
    end
    if !@summoner.nil?
      teams_array = Riot.team(@summoner.riot_id)[@summoner.riot_id.to_s]
      if teams_array.nil?
        flash[:notice] = "No teams found for that summoner"
        render :new
      else
        Team.make(teams_array, @summoner)
        redirect_to summoner_path(@summoner)
      end
    elsif
      flash[:notice] = "Didn't recognize that summoner"
      @summoner = Summoner.new
      render :new
    end
  end

  private
  def summoner_params
    params.require(:summoner).permit(:name)
  end
end

app/views/summoners/new.html.erb
<body id="main">
  <div class="row home fullWidth animated fadeInLeft">
    <div class="small-10 text-center small-centered columns">
      <h1 class="new_title">Teamo</h1>
    </div>
    <div class="bar small-10 medium-9 large-7 small-centered columns">
    <%= form_for @summoner do |s| %>
      <div class="small-10 columns new-bar">
        <%= s.text_field :name, placeholder: "Enter summoner name here"%>
      </div>
      <div class="small-2 columns search-button">
        <%= s.submit "Search", class: "button postfix" %>
    <%- end -%>
      </div>
    </div>
  </div>
</body>

app/views/summoners/show.html.erb
<body id="main">
  <h3 class = "text-center medium-4 medium-centered columns show_title animated fadeInRight"> <%= @summoner.name %> </h3>

  <div class="row home fullWidth animated fadeInRight">
    <div class="small-10 text-center small-centered columns">
        <ul class = "small-block-grid-3 small-centered medium-centered columns">
          <% @teams.each do | t | %>
            <button class="show_button"><%= link_to t.name, team_path(t) %></button>
          <% end %>
        </ul>
    </div>
  </div>
</body>